#+title: Syntax
#+author: Sau P
#+date: 2023-04-17
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}

* Syntax of our language

This language will be a domain specific language specialising in the manipulation of tiles.

** Language specification in Backus-Naur form




#+begin_src java -n
<program> ::= <tile-definitions> <tiling-rules> <functions>
<tile-definitions> ::= <tile-definition> | <tile-definitions> <tile-definition>
<tile-definition> ::= "tile" <tile-name> "{" <cell-rows> "}"
<tile-name> ::= <identifier>
<cell-rows> ::= <cell-row> | <cell-rows> <cell-row>
<cell-row> ::= <cell> | <cell-row> <cell>
<cell> ::= "0" | "1"
<tiling-rules> ::= <tiling-rule> | <tiling-rules> <tiling-rule>
<tiling-rule> ::= <tile-name> "->" <tile-set>
<tile-set> ::= <tile> | <tile-set> <tile>
<tile> ::= <tile-name> | <tile-rotation> <tile>
<tile-rotation> ::= "R" | "L" | "U" | "D"

<functions> ::= <function> | <functions> <function>
<function> ::= "func" <func-name> "(" <parameters> ")" "{" <statements> "}"
<func-name> ::= <identifier>
<parameters> ::= <parameter> | <parameters> "," <parameter>
<parameter> ::= <type> <identifier>
<statements> ::= <statement> | <statements> <statement>
<statement> ::= <variable-declaration> | <function-call> | <loop>
<variable-declaration> ::= <type> <identifier> "=" <expression> ";"
<function-call> ::= <func-name> "(" <arguments> ")" ";"
<arguments> ::= <expression> | <arguments> "," <expression>
<loop> ::= "for" <identifier> "in" <range> "{" <statements> "}"
<range> ::= <expression> ".." <expression>
<expression> ::= <literal> | <variable> | <function-call> | <expression> <operator> <expression>
<operator> ::= "+" | "-" | "*" | "/"

<type> ::= "int" | "float" | "bool" | "string" | <tile-name>
<literal> ::= <int-literal> | <float-literal> | <bool-literal> | <string-literal>
<int-literal> ::= <digit> | <int-literal> <digit>
<float-literal> ::= <int-literal> "." <int-literal>
<bool-literal> ::= "true" | "false"
<string-literal> ::= '"' <characters> '"'
<characters> ::= <char> | <characters> <char>
<char> ::= Any printable ASCII character excluding double quotes(")

<identifier> ::= <alpha> | <identifier> <alpha> | <identifier> <digit>
<alpha> ::= "A" | "B" | ... | "Z" | "a" | "b" | ... | "z" | "_"
<digit> ::= "0" | "1" | ... | "9"

<file> ::= <filename> | <filepath>
<filename> ::= <identifier> "." <extension>
<filepath> ::= <directory> | <filepath> <directory>
<directory> ::= <identifier> "/"
<extension> ::= <identifier>

<read-file> ::= "readFile" "(" <file> ")"
<built-in-function> ::= "print" | "readFile"
<function-call> ::= <func-name> | <built-in-function> "(" <arguments> ")" ";"

#+end_src

** Explanation

*** Program (main)


1. ~<program> ::= <tile-definitions> <tiling-rules> <functions>~
   1. A program consists of tile definitions, tiling rules, and functions.

2. ~<tile-definitions> ::= <tile-definition> | <tile-definitions> <tile-definition>~
   1. Tile definitions can be a single tile definition or multiple tile definitions.

3. ~<tile-definition> ::= "tile" <tile-name> "{" <cell-rows> "}"~
   1. A tile definition starts with the keyword tile, followed by a tile name, an opening curly brace, cell rows, and a closing curly brace.
   2. Example: tile A { 010 101 010 }

4. ~<tile-name> ::= <identifier>~ A tile name is an identifier.

5. ~<cell-rows> ::= <cell-row> | <cell-rows> <cell-row>~
   1. Cell rows can be a single cell row or multiple cell rows.

6. ~<cell-row> ::= <cell> | <cell-row> <cell>~
   1. A cell row can be a single cell or multiple cells.

7. ~<cell> ::= "0" | "1"~
   1. A cell can be either "0" or "1".

8. ~<tiling-rules> ::= <tiling-rule> | <tiling-rules> <tiling-rule>~
   1. Tiling rules can be a single tiling rule or multiple tiling rules.

9. ~<tiling-rule> ::= <tile-name> "->" <tile-set>~
   1. A tiling rule consists of a tile name, followed by the symbol "->", and then a tile set.
   2. Example: A -> B R C L D U

10. ~<tile-set> ::= <tile> | <tile-set> <tile>~
    1. A tile set can be a single tile or multiple tiles.
11.
12. ~<tile> ::= <tile-name> | <tile-rotation> <tile>~
    1. A tile can be a tile name or a tile rotation followed by a tile.
13.
14. ~<tile-rotation> ::= "R" | "L" | "U" | "D"~
    1. A tile rotation can be "R" (right), "L" (left), "U" (upside-down), or "D" (down).

15. ~<functions> ::= <function> | <functions> <function>~
    1. Functions can be a single function or multiple functions.

16. ~<function> ::= "func" <func-name> "(" <parameters> ")" "{" <statements> "}"~
    1. A function is defined with the keyword func, followed by a function name, parameters enclosed in parentheses, and a block of statements enclosed in curly braces.
    2. Example: func add(int a, int b) { int result = a + b; return result; }

17. ~<func-name> ::= <identifier>~
    1. A function name is an identifier.

18. ~<parameters> ::= <parameter> | <parameters> "," <parameter>~
    1. Parameters can be a single parameter or multiple parameters separated by commas.

19. ~<parameter> ::= <type> <identifier>~
    1. A parameter consists of a type and an identifier.

20. ~<statements> ::= <statement> | <statements> <statement>~
    1. Statements can be a single statement or multiple statements.

21. ~<statement> ::= <variable-declaration> | <function-call> | <loop>~
    1. A statement can be a variable declaration, a function call, or a loop.

22. ~<variable-declaration> ::= <type> <identifier> "=" <expression> ";"~
    1. A variable declaration consists of a type, an identifier, an equals sign, an expression, and a semicolon.
    2. Example: int a = 5;

23. ~<function-call> ::= <func-name> "(" <arguments> ")" ";"~
24. A function call consists of a function name, arguments enclosed in parentheses, and a semicolon.
    1. Example: add(3, 4);

25. ~<arguments> ::= <expression> | <arguments> "," <expression>~
26. Arguments can be a single expression or multiple expressions separated by commas.

27. ~<loop> ::= "for" <identifier> "in" <range> "{" <statements> "}"~
    1. A loop consists of the keyword for, an identifier, the keyword in, a range, and a block of statements enclosed in curly braces.
    2. Example: for i in 0..10 { print(i); }

28. ~<range> ::= <expression> ".." <expression>~
    1. A range is defined by two expressions separated by two dots.

29. ~<expression> ::= <literal> | <variable> | <function-call> |~
        ~<expression> <operator> <expression>~
    1. An expression can be a literal, a variable, a function call, or a combination of expressions with an operator.

30. ~<operator> ::= "+" | "-" | "*" | "/"~
    1. An operator can be addition (+), subtraction (-), multiplication (*), or division (/).

31. ~<type> ::= "int" | "float" | "bool" | "string" | <tile-name>~
    1. A type can be an integer (int), a floating-point number (float), a boolean (bool), a string, or a tile name.

32. ~<literal> ::= <int-literal> | <float-literal> | <bool-literal> | <string-literal>~
    1. A literal can be an integer literal, a float literal, a boolean literal, or a string literal.

33. ~<int-literal> ::= <digit> | <int-literal> <digit>~
    1. An integer literal is composed of one or more digits.
    2. Example: 42

34. ~<float-literal> ::= <int-literal> "." <int-literal>~
    1. A float literal is composed of an integer literal, a decimal point, and another integer literal.
    2. Example: 3.14

35. ~<bool-literal> ::= "true" | "false"~
    1. A boolean literal can be either "true" or "false".

36. ~<string-literal> ::= '"' <characters> '"'~
    1. A string literal is composed of characters enclosed in double quotes.
    2. Example: "hello"

37. ~<characters> ::= <char> | <characters> <char>~
    1. Characters can be a single character or multiple characters.

38. ~<char> ::= Any printable ASCII character excluding double quotes(")~
    1. A character can be any printable ASCII character, except for double quotes.

39. ~<identifier> ::= <alpha> | <identifier> <alpha> | <identifier> <digit>~
    1. An identifier is composed of letters, underscores, or digits, but it must start with a letter or underscore.

40. ~<alpha> ::= "A" | "B" | ... | "Z" | "a" | "b" | ... | "z" | "_"~
    1. Alpha characters can be uppercase letters, lowercase letters, or an underscore.

41. ~<digit> ::= "0" | "1" | ... | "9"~
    1. A digit can be any number from 0 to 9.

42. ~<file> ::= <filename> | <filepath>~
    1. A file can be a filename or a filepath.

43. ~<filename> ::= <identifier> "." <extension>~
    1. A filename consists of an identifier, a period, and an extension.
    2. Example: input.txt

44. ~<filepath> ::= <directory> | <filepath> <directory>~
    1. A filepath is composed of one or more directories.
    2. Example: folder1/folder2/input.txt

45. ~<directory> ::= <identifier> "/"~
    1. A directory consists of an identifier followed by a forward slash.

46. ~<extension> ::= <identifier>~
    1. An extension is an identifier.

47. ~<read-file> ::= "readFile" "(" <file> ")"~
    1. Reading a file consists of the keyword readFile, followed by the file enclosed in parentheses.





*** Example: readFile("input.txt")

#+begin_src java
tile A {
  010
  101
  010
}

tile B {
  111
  000
  111
}

A -> B R
B -> A L

func add(int a, int b) {
  int result = a + b;
  return result;
}

func main() {
  int sum = add(3, 4);
  for i in 0..sum {
    print(i);
  }
  string content = readFile("input.txt");
  print(content);
}
#+end_src


** Old Backus-Naur Form

#+begin_src java -n
<program> ::= <tile-definitions> <tiling-rules>
<tile-definitions> ::= <tile-definition> | <tile-definitions> <tile-definition>
<tile-definition> ::= "tile" <tile-name> "{" <cell-rows> "}"
<tile-name> ::= <identifier>
<cell-rows> ::= <cell-row> | <cell-rows> <cell-row>
<cell-row> ::= <cell> | <cell-row> <cell>
<cell> ::= "0" | "1"
<tiling-rules> ::= <tiling-rule> | <tiling-rules> <tiling-rule>
<tiling-rule> ::= <tile-name> "->" <tile-set>
<tile-set> ::= <tile> | <tile-set> <tile>
<tile> ::= <tile-name> | <tile-rotation> <tile>
<tile-rotation> ::= "R" | "L" | "U" | "D"
<identifier> ::= <alpha> | <identifier> <alpha> | <identifier> <digit>
<alpha> ::= "A" | "B" | ... | "Z" | "a" | "b" | ... | "z" | "_"
<digit> ::= "0" | "1" | ... | "9"
#+end_src

*** Explanation

1. A program consists of tile-definitions and tiling-rules.
2. Tile-definitions allows you to compound multiple tiles together.
3. A tile-definition defines a tile with a tile-name and cell-rows.
4. A tile-name is an identifier that uniquely identifies a tile.
5. cell-rows consists of one or more cell-row.
6. A cell-row is a sequence of cell values.
7. A cell is either "0" or "1", representing an empty or filled cell, respectively.
8. tiling-rules specifies how tiles can be combined to form larger tiles.
9. A tiling-rule maps a tile-name to a tile-set.
10. A tile-set consists of one or more tile.
11. A tile can be a tile-name or a rotated tile.
12. A tile-rotation specifies a rotation of a tile, with "R", "L", "U", and "D" representing right, left, up, and down rotations, respectively.
13. An identifier is a sequence of one or more alphanumeric characters or underscores, starting with an alphabet character.
14. An alpha is an uppercase or lowercase alphabet character or underscore.
15. A digit is a number from 0 to 9.
